import base64
import io
import os
from datetime import datetime
from fpdf import FPDF

class PDF(FPDF):
    """Custom PDF class to handle consistent headers and footers."""
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Medical Image Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf_report(result_data):
    """
    Generates a complete PDF report from the analysis data, including the
    original image but excluding the segmentation mask.
    """
    pdf = PDF()
    pdf.add_page()

    # --- Section 1: Patient & Image Details ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Patient & Image Details', 0, 1, 'L')
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 7, f"Patient Name/ID: {result_data.get('patient_name', 'N/A')}", 0, 1)
    pdf.cell(0, 7, f"Original Filename: {result_data.get('filename', 'N/A')}", 0, 1)
    raw_ts = result_data.get('timestamp')
    if raw_ts:
        if raw_ts.endswith('Z'):
            raw_ts = raw_ts[:-1] + '+00:00'
        try:
            formatted_ts = datetime.fromisoformat(raw_ts).strftime('%Y-%m-%d %H:%M:%S')
        except Exception:
            formatted_ts = raw_ts
    else:
        formatted_ts = 'N/A'
    pdf.cell(0, 7, f"Analysis Timestamp: {formatted_ts}", 0, 1)
    pdf.ln(8)

    # --- Section 2: Two-Column Layout ---
    y_after_details = pdf.get_y()
    
    # --- Left Column: Original Image ---
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(95, 8, 'Visual Evidence', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    image_path = result_data.get('image_path', '')
    original_image = result_data.get('original_image', '')

    if image_path and os.path.exists(image_path):
        pdf.cell(0, 7, "Original Image:", 0, 1)
        pdf.image(image_path, w=80)
    else:
        original_image_b64 = ''
        if original_image.startswith('data:'):
            original_image_b64 = original_image.split(',')[-1]
        elif original_image and ',' in original_image:
            original_image_b64 = original_image.split(',')[-1]

        if original_image_b64:
            try:
                image_bytes = base64.b64decode(original_image_b64)
                pdf.cell(0, 7, "Original Image:", 0, 1)
                pdf.image(io.BytesIO(image_bytes), w=80)
            except Exception:
                pdf.cell(0, 7, "Original Image: unavailable", 0, 1)
        elif original_image:
            pdf.cell(0, 7, "Original Image: unavailable", 0, 1)
    
    y_after_images = pdf.get_y()

    # --- Right Column: Analysis Findings ---
    pdf.set_y(y_after_details)
    pdf.set_x(110)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 8, 'Analysis Findings', 0, 1)
    
    classification = result_data.get('classification', {})
    analysis = result_data.get('analysis', {})
    
    pdf.set_x(110)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 7, f"Prediction: {classification.get('predicted_class', 'N/A').upper()}", 0, 1)
    pdf.set_x(110)
    pdf.cell(0, 7, f"Confidence Level: {analysis.get('confidence_level', 'N/A')} ({(classification.get('confidence', 0) * 100):.2f}%)", 0, 1)
    pdf.ln(5)

    pdf.set_x(110)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Recommendation', 0, 1)
    pdf.set_x(110)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(90, 7, analysis.get('recommendation', 'N/A'))
    
    y_after_text = pdf.get_y()

    # --- Section 3: Disclaimer (Full Width) ---
    pdf.set_y(max(y_after_images, y_after_text) + 10)
    
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report was generated by an automated tool and is not a substitute for a professional medical diagnosis.")
    
    return bytes(pdf.output())
